services:
 frontend:
  image: cmc_frontend
  build: 
    context: .
    target: "develop-stage"
  ports: 
    - 8080:8080
    - 8081:8081
    - 8082:8082
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  #command: sh -c "quasar dev"
  command: /bin/sh -c "yarn && quasar upgrade -i && quasar dev"

