version: "3.8"
services:
  frontend:
    image: cmc_frontend_production
    build:
      context: .
      target: production-stage
    ports:
      - "80:80"
      - "443:443"
    # volumes:
    #  - ./:/usr/share/nginx/html
    #  - /etc/ssl/certs/STAR_vims_edu.crt:/etc/nginx/ssl/STAR_vims_edu.crt
    #  - /etc/ssl/private/server.key:/etc/nginx/ssl/server.key